# Generated by Django 5.2.7 on 2025-12-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0004_pair_canonical_unique'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pair',
            new_name='pairs_pair_left_id_e52a11_idx',
            old_name='pairs_pair_left_right_idx',
        ),
        migrations.RenameIndex(
            model_name='pair',
            new_name='pairs_pair_scan_ca_a01847_idx',
            old_name='pairs_pair_scan_cached_idx',
        ),
    ]
