# Generated by Django 5.2.7 on 2025-12-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt5api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyprice',
            new_name='mt5api_dail_ticker_5e0f18_idx',
            old_name='mt5api_dail_ticker__20c920_idx',
        ),
        migrations.RenameIndex(
            model_name='livetick',
            new_name='mt5api_live_ticker_331844_idx',
            old_name='mt5api_live_ticker__61a163_idx',
        ),
    ]
