# Generated by Django 5.2.7 on 2025-12-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt5api', '0002_rename_mt5api_dail_ticker__20c920_idx_mt5api_dail_ticker_5e0f18_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPricePivot',
            fields=[
            ],
            options={
                'verbose_name': 'DailyPrice Pivot',
                'verbose_name_plural': 'DailyPrice Pivot',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mt5api.dailyprice',),
        ),
    ]
